language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install g++-4.8;
      export CXX='g++-4.8';
    fi
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
